k13/DancingGoatMvc/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using CMS.Base;
using CMS.Ecommerce;
using CMS.Globalization;
using CMS.Helpers;

using Kentico.Content.Web.Mvc;

using DancingGoat.ActionSelectors;
using DancingGoat.Models.Checkout;
using DancingGoat.Repositories;
using DancingGoat.Services;

namespace DancingGoat.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IShoppingService shoppingService;
        private readonly ICheckoutService checkoutService;
        private readonly IContactRepository contactRepository;
        private readonly IProductRepository productRepository;
        private readonly IPageUrlRetriever pageUrlRetriever;
        private readonly ISKUInfoProvider skuInfoProvider;
        private readonly ICountryInfoProvider countryInfoProvider;
        private readonly IStateInfoProvider stateInfoProvider;


        public CheckoutController(IShoppingService shoppingService, IContactRepository contactRepository, IProductRepository productRepository, 
            ICheckoutService checkoutService, IPageUrlRetriever pageUrlRetriever, ISKUInfoProvider skuInfoProvider, ICountryInfoProvider countryInfoProvider,
            IStateInfoProvider stateInfoProvider)
        {
            this.shoppingService = shoppingService;
            this.contactRepository = contactRepository;
            this.checkoutService = checkoutService;
            this.productRepository = productRepository;
            this.pageUrlRetriever = pageUrlRetriever;
            this.skuInfoProvider = skuInfoProvider;
            this.countryInfoProvider = countryInfoProvider;
            this.stateInfoProvider = stateInfoProvider;
        }


        public ActionResult ShoppingCart()
        {
            var viewModel = checkoutService.PrepareCartViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult ShoppingCartCheckout()
        {
            var cart = shoppingService.GetCurrentShoppingCart();
            var validationErrors = ShoppingCartInfoProvider.ValidateShoppingCart(cart);

            cart.Evaluate();

            if (!validationErrors.Any())
            {
                var customer = GetCustomerOrCreateFromAuthenticatedUser();
                if (customer != null)
                {
                    shoppingService.SetCustomer(customer);
                }

                shoppingService.SaveCart();
                return RedirectToAction("DeliveryDetails");
            }

            // Fill model state with errors from the check result
            ProcessCheckResult(validationErrors);

            var viewModel = checkoutService.PrepareCartViewModel();

            return View("ShoppingCart", viewModel);
        }


        public ActionResult DeliveryDetails()
        {
            var cart = shoppingService.GetCurrentShoppingCart();
            if (cart.IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = checkoutService.PrepareDeliveryDetailsViewModel();

            return View(viewModel);
        }


        public ActionResult PreviewAndPay()
        {
            if (shoppingService.GetCurrentShoppingCart().IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = checkoutService.PreparePreviewViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreviewAndPay(PreviewViewModel model)
        {
            var cart = shoppingService.GetCurrentShoppingCart();

            if (cart.IsEmpty)
            {
                ModelState.AddModelError("cart.empty", ResHelper.GetString("DancingGoatMvc.Checkout.EmptyCartError"));

                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            if (!checkoutService.IsPaymentMethodValid(model.PaymentMethod.PaymentMethodID))
            {
                ModelState.AddModelError("PaymentMethod.PaymentMethodID", ResHelper.GetString("DancingGoatMvc.Payment.PaymentMethodRequired"));
            }
            else
            {
                shoppingService.SetPaymentOption(model.PaymentMethod.PaymentMethodID);
            }

            var validator = new CreateOrderValidator(cart, skuInfoProvider, countryInfoProvider, stateInfoProvider);

            if (!validator.Validate())
            {
                ProcessCheckResult(validator.Errors);
            }

            if (!ModelState.IsValid)
            {
                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            try
            {
                shoppingService.CreateOrder();
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("cart.createordererror", ex.Message);
                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            return RedirectToAction("ThankYou");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult DeliveryDetails(DeliveryDetailsViewModel model)
        {
            // Check the selected shipping option
            bool isShippingNeeded = shoppingService.GetCurrentShoppingCart().IsShippingNeeded;
            if (isShippingNeeded && !checkoutService.IsShippingOptionValid(model.ShippingOption.ShippingOptionID))
            {
                ModelState.AddModelError("ShippingOption.ShippingOptionID", ResHelper.GetString("DancingGoatMvc.Shipping.ShippingOptionRequired"));
            }

            // Check if the billing address's country and state are valid
            var countryStateViewModel = model.BillingAddress.BillingAddressCountryStateSelector;
            if (!checkoutService.IsCountryValid(countryStateViewModel.CountryID))
            {
                countryStateViewModel.CountryID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.CountryID", ResHelper.GetString("DancingGoatMvc.Address.CountryIsRequired"));
            }
            else if (!checkoutService.IsStateValid(countryStateViewModel.CountryID, countryStateViewModel.StateID))
            {
                countryStateViewModel.StateID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.StateID", ResHelper.GetString("DancingGoatMvc.Address.StateIsRequired"));
            }

            if (!ModelState.IsValid)
            {
                var viewModel = checkoutService.PrepareDeliveryDetailsViewModel(model.Customer, model.BillingAddress, model.ShippingOption);

                return View(viewModel);
            }

            var customer = GetCustomerOrCreateFromAuthenticatedUser() ?? new CustomerInfo();
            bool emailCanBeChanged = !User.Identity.IsAuthenticated || string.IsNullOrWhiteSpace(customer.CustomerEmail);
            model.Customer.ApplyToCustomer(customer, emailCanBeChanged);
            shoppingService.SetCustomer(customer);

            var modelAddressID = model.BillingAddress.BillingAddressSelector?.AddressID ?? 0;
            var billingAddress = checkoutService.GetAddress(modelAddressID) ?? new AddressInfo();

            model.BillingAddress.ApplyTo(billingAddress);
            billingAddress.AddressPersonalName = $"{customer.CustomerFirstName} {customer.CustomerLastName}";

            shoppingService.SetBillingAddress(billingAddress);
            shoppingService.SetShippingOption(model.ShippingOption?.ShippingOptionID ?? 0);

            return RedirectToAction("PreviewAndPay");
        }


        public ActionResult ThankYou()
        {
            var companyContact = contactRepository.GetCompanyContact();

            var viewModel = new ThankYouViewModel
            {
                Phone = companyContact.Phone
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult AddItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                shoppingService.AddItemToCart(item.SKUID, item.Units);
            }

            return RedirectToAction("ShoppingCart");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult UpdateItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                shoppingService.UpdateItemQuantity(item.ID, item.Units);
            }
            else
            {
                // Add an item error and save ViewData so that the ShoppingCart action can show validation errors
                var key = item.ID.ToString();
                ModelState.Add(key, ModelState["Units"]);
            }

            var cartViewModel = checkoutService.PrepareCartViewModel();
            return View("ShoppingCart", cartViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult RemoveItem(CartItemUpdateModel item)
        {
            shoppingService.RemoveItemFromCart(item.ID);

            var cartViewModel = checkoutService.PrepareCartViewModel();
            return View("ShoppingCart", cartViewModel);
        }


        [HttpPost]
        public JsonResult CustomerAddress(int addressID)
        {

k13/DancingGoatMvc/Controllers/CompanyController.cs
using System.Linq;
using System.Web.Mvc;

using DancingGoat.Models.Contacts;
using DancingGoat.Models.SocialLinks;
using DancingGoat.Repositories;

using Kentico.Content.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IContactRepository contactRepository;
        private readonly ICountryRepository countryRepository;
        private readonly ISocialLinkRepository socialLinkRepository;
        private readonly IPageAttachmentUrlRetriever attachmentUrlRetriever;


        public CompanyController(ISocialLinkRepository socialLinkRepository,
            IContactRepository contactRepository,
            ICountryRepository countryRepository, 
            IPageAttachmentUrlRetriever attachmentUrlRetriever)
        {
            this.countryRepository = countryRepository;
            this.socialLinkRepository = socialLinkRepository;
            this.contactRepository = contactRepository;
            this.attachmentUrlRetriever = attachmentUrlRetriever;
        }


        [ChildActionOnly]
        [ValidateInput(false)]
        public ActionResult CompanyAddress()
        {
            var address = GetCompanyContactModel();

            return PartialView("_Address", address);
        }


        [ChildActionOnly]
        [ValidateInput(false)]
        public ActionResult CompanySocialLinks()
        {
            var socialLinks = socialLinkRepository.GetSocialLinks();

            return PartialView("_SocialLinks", socialLinks.Select(link => SocialLinkViewModel.GetViewModel(link, attachmentUrlRetriever)));
        }


        private ContactViewModel GetCompanyContactModel()
        {
            return ContactViewModel.GetViewModel(contactRepository.GetCompanyContact(), countryRepository);
        }
    }
}

k13/DancingGoatMvc/Controllers/ConsentController.cs
using System.Net;
using System.Threading;
using System.Web.Mvc;

using CMS.ContactManagement;
using CMS.DataProtection;
using CMS.Helpers;

using DancingGoat.Helpers.Generator;
using DancingGoat.Models.Consent;

namespace DancingGoat.Controllers
{
    public class ConsentController : Controller
    {
        private readonly ICurrentCookieLevelProvider cookieLevelProvider;
        private readonly IConsentAgreementService consentAgreementService;
        private readonly IConsentInfoProvider consentInfoProvider;


        public ConsentController(ICurrentCookieLevelProvider cookieLevelProvider, IConsentAgreementService consentAgreementService, IConsentInfoProvider consentInfoProvider)
        {
            this.cookieLevelProvider = cookieLevelProvider;
            this.consentAgreementService = consentAgreementService;
            this.consentInfoProvider = consentInfoProvider;
        }


        // GET: Consent
        public ActionResult Index()
        {
            var consent = consentInfoProvider.Get(TrackingConsentGenerator.CONSENT_NAME);
            if (consent != null)
            {
                var model = new ConsentViewModel
                {
                    ConsentShortText = consent.GetConsentText(Thread.CurrentThread.CurrentUICulture.Name).ShortText
                };

                var contact = ContactManagementContext.CurrentContact;
                if ((contact != null) && consentAgreementService.IsAgreed(contact, consent))
                {
                    model.IsConsentAgreed = true;
                }

                return PartialView("_TrackingConsent", model);
            }

            return new EmptyResult();
        }


        // POST: Consent/Agree
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agree()
        {
            var resultStatus = HttpStatusCode.BadRequest;

            var consent = consentInfoProvider.Get(TrackingConsentGenerator.CONSENT_NAME);
            if (consent != null)
            {
                cookieLevelProvider.SetCurrentCookieLevel(CookieLevel.All);
                
                var contact = ContactManagementContext.CurrentContact;
                if (contact != null) 
                { 
                    consentAgreementService.Agree(contact, consent);
                }

                resultStatus = HttpStatusCode.OK;
            }

            // Redirect is handled on client by javascript
            return new HttpStatusCodeResult(resultStatus);
        }
    }
}

k13/DancingGoatMvc/Controllers/SearchController.cs
using System;
using System.Linq;
using System.Threading;
using System.Web.Mvc;

using CMS.Base;
using CMS.Base.Internal;
using CMS.Membership;
using CMS.Search;
using CMS.WebAnalytics;

using DancingGoat.Infrastructure;
using DancingGoat.Models.Search;

using X.PagedList;

namespace DancingGoat.Controllers
{
    public class SearchController : Controller
    {
        private const string INDEX_NAME = "DancingGoatMvc.Index";
        private const int PAGE_SIZE = 5;
        private const int DEFAULT_PAGE_NUMBER = 1;

        private readonly TypedSearchItemViewModelFactory searchItemViewModelFactory;
        private readonly IPagesActivityLogger pagesActivityLogger;
        private readonly IAnalyticsLogger analyticsLogger;
        private readonly ISiteService siteService;
        private readonly IHttpContextRetriever retriever;


        public SearchController(TypedSearchItemViewModelFactory searchItemViewModelFactory, IPagesActivityLogger pagesActivityLogger, 
            IAnalyticsLogger analyticsLogger, ISiteService siteService, IHttpContextRetriever retriever)
        {
            this.searchItemViewModelFactory = searchItemViewModelFactory;
            this.pagesActivityLogger = pagesActivityLogger;
            this.analyticsLogger = analyticsLogger;
            this.siteService = siteService;
            this.retriever = retriever;
        }


        // GET: Search
        [ValidateInput(false)]
        public ActionResult Index(string searchText, int page = DEFAULT_PAGE_NUMBER)
        {
            if (String.IsNullOrWhiteSpace(searchText))
            {
                var empty = new SearchResultsModel
                {
                    Items = new StaticPagedList<SearchResultItemModel>(Enumerable.Empty<SearchResultItemModel>(), page, PAGE_SIZE, 0)
                };
                return View(empty);
            }

            // Validate page number (starting from 1)
            page = Math.Max(page, DEFAULT_PAGE_NUMBER);

            var searchParameters = SearchParameters.PrepareForPages(searchText, new[] { INDEX_NAME }, page, PAGE_SIZE, MembershipContext.AuthenticatedUser);
            var searchResults = SearchHelper.Search(searchParameters);

            pagesActivityLogger.LogInternalSearch(searchText);

            var siteId = siteService.CurrentSite.SiteID;
            var culture = Thread.CurrentThread.CurrentCulture.Name;
            var uri = retriever.GetContext().Request.Url;
            var hostAddress = retriever.GetContext().Request.UserHostAddress;

            analyticsLogger.LogInternalSearchKeywords(new AnalyticsData(siteId, searchText, culture: culture, uri: uri, hostAddress: hostAddress));

            var searchResultItemModels = searchResults.Items
                .Select(searchResultItem => searchItemViewModelFactory.GetTypedSearchResultItemModel(searchResultItem));

            var model = new SearchResultsModel
            {
                Items = new StaticPagedList<SearchResultItemModel>(searchResultItemModels, page, PAGE_SIZE, searchResults.TotalNumberOfResults),
                Query = searchText
            };

            return View(model);
        }
    }
}

k13/DancingGoatMvc/Views/Shared/_GoogleMaps.cshtml
@using CMS.Base

<script src="https://maps.googleapis.com/maps/api/js?key=@SettingsHelper.AppSettings["GoogleMapsApiKey"]"></script>
@Scripts.Render("~/Scripts/map.js")

k13/DancingGoatMvc/Views/Shared/_LandingPageLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head id="head">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8" />
    @Html.Kentico().PageDescription()
    @Html.Kentico().PageKeywords()
    @Html.Kentico().PageTitle()
    <link rel="icon" href="~/content/images/favicon.png" type="image/png" />
    <link href="~/Content/Styles/Landing-page.css" rel="stylesheet" type="text/css" />
    <link rel="canonical" href="@Url.Kentico().PageCanonicalUrl()" />
    @Html.Kentico().PageBuilderStyles()
    @Html.Kentico().ABTestLoggerScript()
</head>
<body>
    <div class="page-wrap">
        @Html.Action("Index", "Consent")
        @RenderBody()
    </div>
    <div class="footer-wrapper">
        <footer>
            <div class="footer-container">
                <div class="container">
                    Copyright &copy; @DateTime.Now.Year Dancing Goat. All rights reserved.
                </div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-unobtrusive-ajax")
    @Scripts.Render("~/bundles/jquery-validation")
    @Html.Kentico().PageBuilderScripts()
    @Html.Kentico().ActivityLoggingScript()
</body>
</html>

k13/DancingGoatMvc/Views/Shared/_Layout.cshtml
@using Kentico.Membership.Web.Mvc
@using Kentico.Content.Web.Mvc
@using DancingGoat.Models.Widgets

<!DOCTYPE html>

<html>
<head id="head">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8" />
    @Html.Kentico().PageDescription()
    @Html.Kentico().PageKeywords()
    @Html.Kentico().PageTitle(ViewBag.Title as string)
    <link rel="icon" href="~/content/images/favicon.png" type="image/png" />
    <link href="~/Content/Styles/Site.css" rel="stylesheet" type="text/css" />
    <link rel="canonical" href="@Url.Kentico().PageCanonicalUrl()" />
    @RenderSection("styles", required: false)
    @Html.Kentico().ABTestLoggerScript()
    @Html.Kentico().ActivityLoggingScript()
    @Html.Kentico().WebAnalyticsLoggingScript()
</head>
<body>
    <div class="page-wrap">
        @Html.Action("Index", "Consent")
        <header class="header" data-ktc-search-exclude>
            <div class="menu">
                <div class="container">
                    @Html.Action("Menu", "Navigation")
                    <div class="menu-separator"></div>
                    <div class="additional-menu-buttons user-menu">
                        <div class="dropdown-header menu-hover">
                            <div class="dropdown-icon-tablet">
                                <i aria-hidden="true" id="user-menu-icon" class="icon-user"></i>
                            </div>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <div class="dropdown-desktop">
                                    <img src="@Url.Kentico().AvatarUrl(User.Identity.Name, pathToDefaultAvatar: "~/Content/Images/default-avatar.png")" class="dropdown-desktop-avatar" alt="avatar" />
                                    @ResHelper.GetStringFormat("DancingGoatMvc.Hello", User.Identity.Name)
                                    <i aria-hidden="true" class="icon-chevron-down dropdown-arrow"></i>
                                </div>
                            }
                            <span id="user-dropdown-caption-opened" class="sr-only">@ResHelper.GetString("DancingGoatMvc.CloseMenu")</span>
                            <span id="user-dropdown-caption-closed" class="sr-only">@ResHelper.GetString("DancingGoatMvc.OpenMenu")</span>
                        </div>
                        <nav>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <ul class="dropdown-items-list">
                                    <li>
                                        @Html.ActionLink(@ResHelper.GetString("DancingGoatMvc.YourAccount"), "YourAccount", "Account")
                                    </li>
                                    <li>
                                        @using (Html.BeginForm("Logout", "Account"))
                                        {
                                            @Html.Kentico().AntiForgeryToken()
                                            <input type="submit" value="@ResHelper.GetString("DancingGoatMvc.SignOut")" class="sign-out-button" />
                                        }
                                    </li>
                                </ul>
                            }
                            else
                            {
                                <ul class="dropdown-items-list dropdown-desktop-visible">
                                    <li>
                                        @Html.ActionLink(ResHelper.GetString("DancingGoatMvc.Register"), "Register", "Account")
                                    </li>
                                    <li>
                                        @Html.ActionLink(ResHelper.GetString("DancingGoatMvc.SignIn"), "Login", "Account")
                                    </li>
                                </ul>
                            }
                        </nav>
                    </div>
                    <div class="menu-separator"></div>
                    @if (Response.StatusCode == (int)HttpStatusCode.OK)
                    {
                        <div class="additional-menu-buttons languages">
                            <div class="dropdown-header menu-hover dropdown-header-mobile">
                                <div class="dropdown-icon-tablet">
                                    <i aria-hidden="true" id="language-selection-icon" class="icon-earth"></i>
                                </div>
                                <div class="dropdown-desktop dropdown-mobile">
                                    @ResHelper.GetString("DancingGoatMvc.Culture." + System.Threading.Thread.CurrentThread.CurrentCulture.Name)
                                    <i aria-hidden="true" id="language-select-btn" class="icon-chevron-down dropdown-arrow">  </i>
                                </div>
                                <span id="language-select-caption-opened" class="sr-only">@ResHelper.GetString("DancingGoatMvc.CloseSelector")</span>
                                <span id="language-select-caption-closed" class="sr-only">@ResHelper.GetString("DancingGoatMvc.OpenSelector")</span>
                            </div>
                            <nav>
                                <ul class="dropdown-items-list dropdown-items-list-mobile">
                                    <li>
                                        @Html.CultureLink(ResHelper.GetString("DancingGoatMvc.Culture.en-us"), "en-US")
                                    </li>
                                    <li>
                                        @Html.CultureLink(ResHelper.GetString("DancingGoatMvc.Culture.es-es"), "es-ES")
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    }
                </div>
            </div>
            <div class="header-row">
                <div class="container">
                    <div class="col-xs-2 md-hidden lg-hidden">
                        <button type="button" id="mobile-menu-btn">
                            <i aria-hidden="true" id="mobile-menu-icon" class="icon-menu"></i>
                            <span id="mobile-menu-caption" class="sr-only">@ResHelper.GetString("DancingGoatMvc.OpenMenu")</span>
                        </button>
                    </div>
                    <div class="col-xs-8 col-md-12 col-lg-4 logo">
                        <h1 class="logo">
                            @Html.HtmlLink(Url.Kentico().PageUrl(ContentItemIdentifiers.HOME), "Dancing Goat", new { @class = "logo-link" })
                        </h1>

                    </div>
                    <div class="col-xs-2 md-hidden lg-hidden cart-preview-mini">
                        <a href="@Url.Action("ShoppingCart", "Checkout")" class="shopping-cart">
                            <i aria-hidden="true" class="icon-shopping-cart"></i>
                            <span class="sr-only">@ResHelper.GetString("DancingGoatMvc.ShoppingCart")</span>
                        </a>
                    </div>
                    <div class="col-xs-12 col-md-7 col-lg-4">
                        @using (Html.BeginForm("Index", "Search", FormMethod.Get, new { @Id = "searchForm", @Class = "searchBox" }))
                        {
                            <input type="text" id="searchtext" name="searchtext" placeholder="@ResHelper.GetString("DancingGoatMvc.Search")" maxlength="1000" class="search-box-watermark" autocomplete="off">
                            <input type="submit" value="" class="search-box-btn">
                        }
                    </div>
                    <div class="col-md-5 col-lg-4 xs-hidden sm-hidden">
                        <div class="shopping-cart-mini-preview">
                            <a href="@Url.Action("ShoppingCart", "Checkout")">
                                <div class="shopping-cart-mini-preview-label">
                                    @ResHelper.GetString("DancingGoatMvc.YourCart")
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <div class="footer-wrapper">
        <footer data-ktc-search-exclude>
            <div class="footer-container">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-lg-3 footer-col">
                            <h3 class="contact-title">@ResHelper.GetString("DancingGoatMvc.Contact.Title")</h3>
                            <p>
                                @Html.Action("CompanyAddress", "Company")
                            </p>
                        </div>
                        <div class="col-md-4 col-lg-6 footer-col">
                            <div class="col-md-12 col-lg-6 footer-zone-follow-us">
                                <h3>@ResHelper.GetString("DancingGoatMvc.FollowUs.Title")</h3>
                                @Html.Action("CompanySocialLinks", "Company")
                            </div>

                            <div class="col-md-12 col-lg-6">
                                @Html.Action("Footer", "Navigation")
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-3 footer-col">
                            <h3>@ResHelper.GetString("DancingGoatMvc.News.Title")</h3>
                            @Html.Kentico().RenderStandaloneWidget(DancingGoat.Controllers.Widgets.NewsletterSubscriptionWidgetController.IDENTIFIER, new NewsletterSubscriptionProperties())
                        </div>
                    </div>
                </div>
            </div>
            <div class="container copyright">
                Copyright &copy; @DateTime.Now.Year Dancing Goat. All rights reserved.
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-unobtrusive-ajax")
    @Scripts.Render("~/bundles/jquery-validation")
    @Scripts.Render("~/Scripts/responsiveMenuDropdown.js")
    @Scripts.Render("~/Scripts/mobileMenu.js")

    @RenderSection("scripts", required: false)

</body>
</html>

k13/DancingGoatMvc/Views/Shared/_ManufacturerList.cshtml
@using DancingGoat.Models.Manufacturers;
@model IEnumerable<ManufactureListItemViewModel>

    <div class="row manufacturer-list">
        @if (Model != null && Model.Any())
        {
            foreach (var manufacturer in Model)
            {
                <div class="col-md-4 col-lg-3 manufacturer-item">
                    <a href="@manufacturer.Url">
                        <img src="@manufacturer.ImagePath" alt="@manufacturer.Name" />
                    </a>
                </div>
            }
        }
        else
        {
            <span class="ContentLabel">@ResHelper.GetString("DancingGoatMvc.Manufacturers.NoMatchingManufacturers")</span>
        }
    </div>

k13/DancingGoatMvc/Views/Shared/_StoreProductList.cshtml
@using DancingGoat.Models.Products
@model IEnumerable<ProductListItemViewModel>
    
@if (Model.Any())
{
    foreach (var product in Model)
    {
        <!-- 4 products on row for large screen -->
        <div class="col-md-4 col-lg-3">
            @Html.DisplayFor(m => product, "ProductListItem")
        </div>
    }
}
else
{
    <span class="ContentLabel">@ResHelper.GetString("DancingGoatMvc.Store.NoMatchingProducts")</span>
}

k13/DancingGoatMvc/Views/Shared/_TrackingConsent.cshtml
@model DancingGoat.Models.Consent.ConsentViewModel

<div id="consent" class="cookie-consent" data-ktc-search-exclude>
    @if (!Model.IsConsentAgreed)
    {
        <div class="consent-text">@Model.ConsentNotAgreedText</div>
        <div>@Model.ConsentShortText</div>
        using (Ajax.BeginForm("Agree", "Consent", new AjaxOptions { HttpMethod = "Post", OnComplete = "new function(){window.location.reload()}" }, new { @class = "consent-buttons" }))
        {
            @Html.Kentico().AntiForgeryToken()
            <input type="submit" value="@Model.AgreeButtonText" class="btn btn-default btn-consent">
        }
    }
    else
    {
        <div>
            @Model.ConsentAgreedText @Html.HtmlLink(Url.Kentico().PageUrl(ContentItemIdentifiers.PRIVACY), Model.PrivacyPageLinkText).
        </div>
    }
</div>